### ISSUE TITLE
Its not rendering the previously selected values.

### ISSUE THREAD

**Issue by sugacrmblog** [markcunninghamuk/PCF_Library#12]
On create of of records, multiselect is working fine and able to select multiple records.
Upon save, its not rendering the selected records.

**Comment by JasonMcAndrew** [comment]
I am also experiencing this same issue. Is there some additional config required for this to work?

**Comment by markcunninghamuk** [comment]
Try with this example and see if it works

![image](https://github.com/markcunninghamuk/PCF_Library/assets/22330376/309f9031-3a59-4b01-85c6-adfaf0253b3c)

**Comment by JasonMcAndrew** [comment]
Hi Mark, 

Thank you for your support and taking the time to reply.

I did try your example above but still had the same issue, however I've upgraded to the latest solution (1.0.0.3) and it's now working as expected.

Thanks
Jason

**Comment by markcunninghamuk** [comment]
Great stuff glad the latest fix worked

Sent from Outlook for Android<https://aka.ms/AAb9ysg>
________________________________
