### ISSUE TITLE
Filter is not working

### ISSUE THREAD

**Issue by ashu-ai** [markcunninghamuk/PCF_Library#15]
console.log("called notifySearch");
        let accountid= Xrm.Page.getAttribute('elogic_account').getValue()[0].id;
		console.log(this.props.entityName,`?$select=${this.props.columns}&$filter=contains(${this.props.filterField}, '${newValue}' and elogic_account eq '${accountid}' '${newValue}')&$top=${this.props.topCount}`);
        
        console.log(accountid);
		return this._context.webAPI.retrieveMultipleRecords(this.props.entityName,`?$select=${this.props.columns}&$filter=contains(${this.props.filterField}, **'${newValue}' and elogic_account eq '${accountid}'**_ &$top=${this.props.topCount}`)
		.then(function (results) {		
				return results?.entities;		__
		})

**Comment by markcunninghamuk** [comment]
more info needed
