### ISSUE TITLE
Selected values disappear from field in form after refresh

### ISSUE THREAD

**Issue by StrategicRetirementPartners** [markcunninghamuk/PCF_Library#16]
1. Open a record to modify the text field configured with MultiSelectPCFControl
2. Select at least one option from the list
3. Save the record and navigate away and navigate back (or refresh using button on white ribbon or browser refresh)
4. Data in field is not there

Note that at any point if I add the column to a view, the data is preserved.

Dynamics Version 1710 (9.2.23034.228) online

![PCF](https://user-images.githubusercontent.com/120495704/236015771-0603521c-141b-4ba8-a03a-f3d8193892aa.gif)

**Comment by markcunninghamuk** [comment]
Interesting are you able to supply me the properties you have set and the entity definition you are binding to. I have not seen this issue before

Sent from Outlook for Android<https://aka.ms/AAb9ysg>
________________________________
From: StrategicRetirementPartners ***@***.***>
Sent: Wednesday, May 3, 2023 7:55:05 PM
To: markcunninghamuk/PCF_Library ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [markcunninghamuk/PCF_Library] Selected values disappear from field in form after refresh (Issue #16)


  1.  Open a record to modify the text field configured with MultiSelectPCFControl
  2.  Select at least one option from the list
  3.  Save the record and navigate away and navigate back (or refresh using button on white ribbon or browser refresh)
  4.  Data in field is not there

Note that at any point if I add the column to a view, the data is preserved.

Dynamics Version 1710 (9.2.23034.228) online

[PCF]<https://user-images.githubusercontent.com/120495704/236015771-0603521c-141b-4ba8-a03a-f3d8193892aa.gif>

**Comment by StrategicRetirementPartners** [comment]
I've tried a variety but from the clip it was this.
![image](https://user-images.githubusercontent.com/120495704/236498171-07850821-3865-4030-a2e2-267d4ade2a50.png)
If I use systemuserid instead of fullname for the valueField, the id is visible in the view instead of the name but otherwise same behavior.

**Comment by cbalentod** [comment]
I am getting the same issue.  It displays the dropdown correctly.  And it saves the unique id into the dataverse as a comma delimited value.  But it does not re-populate the values when you open the form.

**Comment by markcunninghamuk** [comment]
Is the field you are displaying in the view?

Sent from Outlook for Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by markcunninghamuk** [comment]
I have replicated the issue, the issue is you are not storing the systemuserId so when the form loads it tries to find a userid with the value of the fullname which is clearly wrong as it needs to be a gui

**Comment by vissund** [comment]
I have tried exactly as you mentioend in your video https://www.youtube.com/watch?v=InKGTOtY_fA, Just as mentioned by StratgicRetirementPartners ( the above user)  he has already tried keeping the systemuserid, then the value is not persisting in the field. Dear Mark, I have tried EXACTLY as show in your youtube video but still the values are getting cleared on Refresh.
