### ISSUE TITLE
Data is Saved and not rendering after refresh

### ISSUE THREAD

**Issue by PottiArun** [markcunninghamuk/PCF_Library#18]
Hi Mark,

Saw your youtube video for resolving this issue and I followed the same steps that you had followed, but still the control is not rendering the values, even after using the id field.

![image](https://github.com/markcunninghamuk/PCF_Library/assets/118173154/c1314d7b-ed70-49e5-a8f2-531b0bb37c78)

Please help.

**Comment by GauravPandey91** [comment]
Hi Mark,

I am also facing the same issue as mentioned by Arun. Please help

**Comment by ongrieh** [comment]
Same here...did the exact same setup. Please help, @markcunninghamuk :-)

**Comment by markcunninghamuk** [comment]
Good evening everyone, are you able to confirm you are using version 1.0.0.3 from this link?
https://github.com/markcunninghamuk/PCF_Library/releases/tag/1.0.0.3

**Comment by GauravPandey91** [comment]
@markcunninghamuk with this latest update it is working now. 
Can we also extend the control to open the record in popup to have a quick view of the selected record

**Comment by ongrieh** [comment]
> Good evening everyone, are you able to confirm you are using version 1.0.0.3 from this link? https://github.com/markcunninghamuk/PCF_Library/releases/tag/1.0.0.3

 1.0.0.3 did the trick. Thanks a lot 👍

**Comment by ongrieh** [comment]
> Good evening everyone, are you able to confirm you are using version 1.0.0.3 from this link? https://github.com/markcunninghamuk/PCF_Library/releases/tag/1.0.0.3

 1.0.0.3 did the trick. Thanks alot 👍
