### ISSUE TITLE
No display on saved record.

### ISSUE THREAD

**Issue by sstewarta** [markcunninghamuk/PCF_Library#22]
I cannot get the field to return the value after saving. I have every field assigned as you have shown in your video but when you return to the form it will not display the saved item. I look at the field and it is properly recording the GUIDs and the proper names are appearing in the dropdown. Any thought as to why this is?

**Comment by zefannyarp** [comment]
Hi, I'm having the same issue. I've followed exactly like you have shown in your video for the control setup, still won't work.

**Comment by markcunninghamuk** [comment]
both using version 1.0.0.3 right??

**Comment by markcunninghamuk** [comment]
Happy to setup a call with you both to see what the issue can be..

**Comment by sstewarta** [comment]
I ended up making my own PCF component to meet my needs. I was short on time, but I was using the 1.0.0.3.

**Comment by zefannyarp** [comment]
After I checked I wasn't using the latest version (1.0.0.3). I've upgraded it and it works! Thank you.
