### ISSUE TITLE
Field cleared after refresh.

### ISSUE THREAD

**Issue by dim895** [markcunninghamuk/PCF_Library#3]
Hello,

I installed your above solution in our trial environment for testing purposes and enabled it and it works as expected until we “Save” and Refresh.

Once I save, the field is populated both server and client (which is awesome) but when I save and refresh, values are still server side but on the form it looks like it is emplty.

It is really confusing for end users as they arrive on a blank field.

Am I the only one facing this issue?

Thanks in advance,

Best regards
Dimitri
[PCF.pptx](https://github.com/markcunninghamuk/PCF_Library/files/5744379/PCF.pptx)

**Comment by markcunninghamuk** [comment]
Sorry to hear that.it is not an issue I have seen.more than happy to discuss with you.

Get Outlook for Android<https://aka.ms/ghei36>
________________________________

**Comment by markcunninghamuk** [comment]
Ah I now understand after looking. You want a way to show the selected values. This is something I can work on. It will need some extra code.

Get Outlook for Android<https://aka.ms/ghei36>
________________________________

**Comment by dim895** [comment]
Hello,

Yes you got it right, this is exactly what we need so that users:

- can see what has been chosen
- make it possible for them to edit the field.

I guess this is something that will certainly help other too.

Best regards,

Dimtiri

**Comment by voiceman702** [comment]
would definitely love this feature as well!

**Comment by sbv1990** [comment]
Hi @markcunninghamuk @dim895 

I would like to thank you so much for the innovative idea. I have tried this component in one of my model driven apps and facing the same issue. Can you please help me to know if it is something fixed? If so, can you please share updated solution or a code snippent?

Thanks in advance for your help.
 
Regards,
SB

**Comment by markcunninghamuk** [comment]
Add an issue to repo and I will try look at it soon.

Get Outlook for Android<https://aka.ms/ghei36>

________________________________

**Comment by sbv1990** [comment]
Hi @markcunninghamuk,

Thanks for your prompt reply.

It is the same issue, when I save, selected values are getting saved correctly but when I refresh, values are not getting prepopulated from previous save it looks like it is empty. 

Regards,
SB

**Comment by markcunninghamuk** [comment]
Hi all, I am making some progress on this issue, I am working on it this week.

**Comment by markcunninghamuk** [comment]
I have tried with the react select component, sadly I cannot get it to work. I am not sure if its a bug with react-select and defaultOptions

**Comment by markcunninghamuk** [comment]
Can you try the latest version 1.0.0.2 from the releases section. Please close the issue if it works for you.

**Comment by markcunninghamuk** [comment]
Its working, I have tested it in a fresh environment. Closing this issue.
