### ISSUE TITLE
Initial Dropdown Down Scaling

### ISSUE THREAD

**Issue by Cold-Seven** [markcunninghamuk/PCF_Library#8]
There appears to be an issue with the initial dropdown, scaling the window to fit the 10 rows displayed, leaving a black bar at the bottom of the form. This only happens on installation of the dropdown if its near the bottom of the form and the dropdown extends past the size of the form. Are you able to fix this?

![Capture1](https://user-images.githubusercontent.com/94787203/168243900-8efef6bf-25de-4ee3-b386-04b03789324d.PNG)

**Comment by markcunninghamuk** [comment]
that is odd, likely it is an overflow style from the react-select tool. I will try to reproduce

**Comment by markcunninghamuk** [comment]
I have been unable to reproduce it

**Comment by markcunninghamuk** [comment]
gone cold
