### ISSUE TITLE
Saved Values Not Displaying On Initial Open

### ISSUE THREAD

**Issue by amadsenBerg** [markcunninghamuk/PCF_Library#9]
Opening a record every time requires a refresh in order to display the saved values in the picker. Either a browser refresh or Dynamics 365 'Refresh' button is required. Refreshing with an API call does not work.

**Comment by markcunninghamuk** [comment]
Are you using the latest version?

**Comment by amadsenBerg** [comment]
Yes, I'm using 1.0.0.3

**Comment by markcunninghamuk** [comment]
maybe lets do an offline call, you can setup something and invite me mark_cunningham@outlook.com

**Comment by amadsenBerg** [comment]
My apologies, I have mistaken the control- please disregard.
